// <auto-generated />
using System;
using Fast_Bank.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fast_Bank.Infrastructure.Migrations
{
    [DbContext(typeof(DdContext))]
    [Migration("20260223000730_AddEstadoColumnToCuentas")]
    partial class AddEstadoColumnToCuentas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Cedula");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Domain.Entities.ControlEjecucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Proceso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UltimaEjecucion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ControlEjecuciones");
                });

            modelBuilder.Entity("Domain.Entities.Cuenta", b =>
                {
                    b.Property<string>("NumeroCuenta")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteCedula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Activa");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("TEXT");

                    b.Property<double>("Saldo")
                        .HasColumnType("REAL");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("NumeroCuenta");

                    b.HasIndex("ClienteCedula")
                        .IsUnique();

                    b.ToTable("Cuentas", (string)null);

                    b.HasDiscriminator<string>("TipoCuenta").HasValue("Cuenta");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Movimiento", b =>
                {
                    b.Property<string>("IdMovimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinoNumeroCuenta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("Monto")
                        .HasColumnType("REAL");

                    b.Property<string>("OrigenNumeroCuenta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("DestinoNumeroCuenta");

                    b.HasIndex("OrigenNumeroCuenta");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("Domain.Entities.TarjetaCredito", b =>
                {
                    b.Property<string>("NumeroTarjeta")
                        .HasColumnType("TEXT");

                    b.Property<double>("CreditoDisponible")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("LimiteCredito")
                        .HasColumnType("REAL");

                    b.Property<double>("PagoMinimo")
                        .HasColumnType("REAL");

                    b.Property<double>("SaldoUtilizado")
                        .HasColumnType("REAL");

                    b.Property<double>("TasaInteresMensual")
                        .HasColumnType("REAL");

                    b.HasKey("NumeroTarjeta");

                    b.HasIndex("IdCliente")
                        .IsUnique();

                    b.ToTable("TarjetasCredito");
                });

            modelBuilder.Entity("Domain.Entities.CuentaAhorros", b =>
                {
                    b.HasBaseType("Domain.Entities.Cuenta");

                    b.HasDiscriminator().HasValue("Ahorros");
                });

            modelBuilder.Entity("Domain.Entities.CuentaCorriente", b =>
                {
                    b.HasBaseType("Domain.Entities.Cuenta");

                    b.Property<double>("InteresSobregiro")
                        .HasColumnType("REAL");

                    b.Property<double>("LimiteSobregiro")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Corriente");
                });

            modelBuilder.Entity("Domain.Entities.Cuenta", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithOne("Cuenta")
                        .HasForeignKey("Domain.Entities.Cuenta", "ClienteCedula");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Domain.Entities.Movimiento", b =>
                {
                    b.HasOne("Domain.Entities.Cuenta", "Destino")
                        .WithMany("Movimientos")
                        .HasForeignKey("DestinoNumeroCuenta");

                    b.HasOne("Domain.Entities.Cuenta", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenNumeroCuenta")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Destino");

                    b.Navigation("Origen");
                });

            modelBuilder.Entity("Domain.Entities.TarjetaCredito", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithOne("TarjetaCredito")
                        .HasForeignKey("Domain.Entities.TarjetaCredito", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Cuenta");

                    b.Navigation("TarjetaCredito");
                });

            modelBuilder.Entity("Domain.Entities.Cuenta", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
