// <auto-generated />
using System;
using Fast_Bank.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fast_Bank.Infrastructure.Migrations
{
    [DbContext(typeof(DdContext))]
    partial class DdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Cedula");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Domain.Entities.ControlEjecucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Proceso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UltimaEjecucion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ControlEjecuciones");
                });

            modelBuilder.Entity("Domain.Entities.Cuenta", b =>
                {
                    b.Property<string>("NumeroCuenta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("NumeroCuenta");

                    b.ToTable("Cuentas", (string)null);

                    b.HasDiscriminator<string>("TipoCuenta").HasValue("Cuenta");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.EntidadFinanciera", b =>
                {
                    b.Property<string>("IdEntidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdEntidad");

                    b.ToTable("EntidadesFinancieras");
                });

            modelBuilder.Entity("Domain.Entities.Movimiento", b =>
                {
                    b.Property<string>("IdMovimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinoNumeroCuenta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrigenNumeroCuenta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("DestinoNumeroCuenta");

                    b.HasIndex("OrigenNumeroCuenta");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("Domain.Entities.TarjetaCredito", b =>
                {
                    b.Property<string>("NumeroTarjeta")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteCedula")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LimiteCredito")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("TEXT");

                    b.HasKey("NumeroTarjeta");

                    b.HasIndex("ClienteCedula");

                    b.ToTable("TarjetasCredito");
                });

            modelBuilder.Entity("Domain.Entities.CuentaAhorros", b =>
                {
                    b.HasBaseType("Domain.Entities.Cuenta");

                    b.Property<double>("TasaInteres")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Ahorros");
                });

            modelBuilder.Entity("Domain.Entities.CuentaCorriente", b =>
                {
                    b.HasBaseType("Domain.Entities.Cuenta");

                    b.Property<decimal>("LimiteSobregiro")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Corriente");
                });

            modelBuilder.Entity("Domain.Entities.Movimiento", b =>
                {
                    b.HasOne("Domain.Entities.Cuenta", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoNumeroCuenta");

                    b.HasOne("Domain.Entities.Cuenta", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenNumeroCuenta");

                    b.Navigation("Destino");

                    b.Navigation("Origen");
                });

            modelBuilder.Entity("Domain.Entities.TarjetaCredito", b =>
                {
                    b.HasOne("Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCedula");

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
